#!/usr/bin/with-contenv bash

echo 'Creating New Dynamic NBUser...'

if id "${NAMESPACE}" &>/dev/null; then
    echo "User ${NAMESPACE} already is setup"
else
    useradd -M -s /bin/bash -N -u "$((${NB_UID} + 1))" "${NAMESPACE}"
    usermod -aG sudo "${NAMESPACE}"
    mkdir -p "/home/${NAMESPACE}"
    cp -r "/home/jovyan/.conda" "/home/${NAMESPACE}"
    cp -r "/home/jovyan/.jupyter" "/home/${NAMESPACE}"
    chown -R "${NAMESPACE}:users" "/home/${NAMESPACE}"
    chown -R "${NAMESPACE}:users" /usr/local/bin
    chown -R "${NAMESPACE}:users" /etc/s6

    echo ". /opt/conda/etc/profile.d/conda.sh" >> "/home/${NAMESPACE}/.bashrc"
    echo "conda activate base" >> "/home/${NAMESPACE}/.bashrc"

    chown -R ${NAMESPACE}:users ${CONDA_DIR}
    chown -R ${NAMESPACE}:users "/home/jovyan"  
fi

echo "Done."