#!/usr/bin/with-contenv bash

export SHELL='/bin/bash'
cd "/home/${NAMESPACE}"
exec s6-setuidgid ${NAMESPACE} \
  /opt/conda/bin/jupyter lab \
  --notebook-dir="/home/${NAMESPACE}" \
  --ip=0.0.0.0 \
  --no-browser \
  --allow-root \
  --port=8888 \
  --ServerApp.token="" \
  --ServerApp.password="" \
  --ServerApp.allow_origin="*" \
  --ServerApp.base_url="${NB_PREFIX}" \
  --ServerApp.authenticate_prometheus=False

# exec /opt/conda/bin/jupyter lab \
#   --notebook-dir="${HOME}" \
#   --ip=0.0.0.0 \
#   --no-browser \
#   --allow-root \
#   --port=8888 \
#   --ServerApp.token="" \
#   --ServerApp.password="" \
#   --ServerApp.allow_origin="*" \
#   --ServerApp.base_url="${NB_PREFIX}" \
#   --ServerApp.authenticate_prometheus=False